[package]
name = "laszip"
version = "0.1.2"
authors = ["Ruben Nijveld <ruben@tweedegolf.com>", "Erik Jonkers <erik@tweedegolf.com>"]
edition = "2018"

[dependencies]
laszip-sys = { path = "../laszip-sys" }
libc = "0.2.71"
