[package]
name = "laszip-sys"
version = "0.1.1"
authors = ["Ruben Nijveld <ruben@tweedegolf.com>"]
edition = "2018"
build = "build.rs"
links = "laszip"

[build-dependencies]
bindgen = "0.54.0"
cmake = "0.1.44"
